### ISSUE TITLE
Issue sorting case statements

### ISSUE THREAD

**Issue by k2snowman69** [snowcoders/sortier#11]
Input:
```
let type: string = "ForStatement";
switch (type) {
    case "ImportDeclaration": {
        break;
    }

    case "IfStatement": {
        break;
    }
    case "ForStatement":
    case "WhileStatement":
    case "ForOfStatement": {
        break;
    }
    default:
      break;
}
```
Expected Output:
```
let type: string = "ForStatement";
switch (type) {
    case "IfStatement": {
        break;
    }
    case "ImportDeclaration": {
        break;
    }`
    case "ForStatement":
    case "WhileStatement":
    case "ForOfStatement": {
        break;
    }
    default:
      break;
}
```

Actual:
     TypeError: Cannot read property 'range' of undefined
      at Object.reorderValues (D:\Projects\sortier\src\common\sort-utils.ts:16:42)
      at Object.sortSwitchCase (D:\Projects\sortier\src\sortSwitchCase\index.ts:142:27)
      at Context.it (D:\Projects\sortier\src\sortSwitchCase\index.test.ts:70:26)
      at callFn (D:\Projects\sortier\node_modules\mocha\lib\runnable.js:354:21)
      at Test.Runnable.run (D:\Projects\sortier\node_modules\mocha\lib\runnable.js:346:7)
      at Runner.runTest (D:\Projects\sortier\node_modules\mocha\lib\runner.js:442:10)
      at D:\Projects\sortier\node_modules\mocha\lib\runner.js:560:12
      at next (D:\Projects\sortier\node_modules\mocha\lib\runner.js:356:14)
      at D:\Projects\sortier\node_modules\mocha\lib\runner.js:366:7
      at next (D:\Projects\sortier\node_modules\mocha\lib\runner.js:290:14)
      at Immediate._onImmediate (D:\Projects\sortier\node_modules\mocha\lib\runner.js:334:5)
      at runCallback (timers.js:773:18)
      at tryOnImmediate (timers.js:734:5)
      at processImmediate [as _immediateCallback] (timers.js:711:5)

**Comment by k2snowman69** [comment]
https://github.com/snowcoders/sortier/commit/e016e35d37d37711790d8d94d5bfefd2bb3dc7e5
