### ISSUE TITLE
TypeError: Expected `cwd` to be of type `string` but received type `undefined`

### ISSUE THREAD

**Issue by k2snowman69** [snowcoders/sortier#307]
# Language
All

# Input
Running sortier results in the following failure when running with dir-glob 2.2.x
```
TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports.sync (/Users/ricpatel/dev/payx/website/node_modules/dir-glob/index.js:60:9)
    at globDirs (/Users/ricpatel/dev/payx/website/node_modules/globby/index.js:58:9)
    at getPattern (/Users/ricpatel/dev/payx/website/node_modules/globby/index.js:61:64)
    at globTasks.reduce (/Users/ricpatel/dev/payx/website/node_modules/globby/index.js:107:19)
    at Array.reduce (<anonymous>)
    at Function.module.exports.sync (/Users/ricpatel/dev/payx/website/node_modules/globby/index.js:106:26)
    at Object.run (/Users/ricpatel/dev/payx/website/node_modules/@snowcoders/sortier/dist/cli/index.js:17:18)
    at Object.<anonymous> (/Users/ricpatel/dev/payx/website/node_modules/@snowcoders/sortier/bin/index.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

Possibly related to https://github.com/kevva/dir-glob/issues/15 but still seeing the issue

**Comment by k2snowman69** [comment]
Looks like this has something to do with globby@8.0.0... I'm going to release 2.5.1 with globby 9.0.0 and hopefully that may clear things up for you.
