### ISSUE TITLE
Type causes TypeError: Cannot read property 'typeAnnotation' of undefined

### ISSUE THREAD

**Issue by Martaver** [snowcoders/sortier#812]
# Language
Typescript

# Sample input source code
```
export type Json<T extends object> = {
  (value: string): string;
  (value: T): string;
};
```

# Expected output
Not an error.

# Actual output (or error message)
```
Sorting /Users/martaver/Projects/bernie/git/app/cleric/packages/meta/src/generators/json.ts has failed!
If this is an issue with sortier please provide an issue in Github with minimal source code to reproduce the issue
TypeError: Cannot read property 'typeAnnotation' of undefined
/Users/martaver/Projects/bernie/git/app/cleric/node_modules/@snowcoders/sortier/dist/cli/index.js:40
            throw error;
            ^

TypeError: Cannot read property 'typeAnnotation' of undefined
    at getSortGroupIndex (/Users/martaver/Projects/bernie/git/app/cleric/node_modules/@snowcoders/sortier/dist/language-js/sortTSPropertySignatures/index.js:55:33)
    at /Users/martaver/Projects/bernie/git/app/cleric/node_modules/@snowcoders/sortier/dist/language-js/sortTSPropertySignatures/index.js:15:30
    at Array.sort (<anonymous>)
    at /Users/martaver/Projects/bernie/git/app/cleric/node_modules/@snowcoders/sortier/dist/language-js/sortTSPropertySignatures/index.js:14:48
    at Array.forEach (<anonymous>)
    at Object.sortTSPropertySignatures (/Users/martaver/Projects/bernie/git/app/cleric/node_modules/@snowcoders/sortier/dist/language-js/sortTSPropertySignatures/index.js:12:23)
    at Reprinter.rewriteNodes (/Users/martaver/Projects/bernie/git/app/cleric/node_modules/@snowcoders/sortier/dist/language-js/reprinter/index.js:445:67)
    at Reprinter.rewriteNodes (/Users/martaver/Projects/bernie/git/app/cleric/node_modules/@snowcoders/sortier/dist/language-js/reprinter/index.js:275:45)
    at Reprinter.getRewrittenContents (/Users/martaver/Projects/bernie/git/app/cleric/node_modules/@snowcoders/sortier/dist/language-js/reprinter/index.js:27:21)
    at Function.rewriteFile (/Users/martaver/Projects/bernie/git/app/cleric/node_modules/@snowcoders/sortier/dist/reprinter/index.js:38:40)
```

**Comment by k2snowman69** [comment]
Nifty, working on it!

**Comment by k2snowman69** [comment]
Will go out with 3.0.3 or greater
