### ISSUE TITLE
Double spread causes a crash

### ISSUE THREAD

**Issue by k2snowman69** [snowcoders/sortier#84]
Input
```
return <input prop1={1} prop2={2} {...{}} {...{}}  prop3={3} prop4={4} />;
```

Actual: 
      at element.nodes.slice.sort (D:\Projects\sortier\src\sortJsxElement\index.ts:30:23)
      at Array.sort (native)
      at groupings.forEach.element (D:\Projects\sortier\src\sortJsxElement\index.ts:29:49)
      at Array.forEach (<anonymous>)
      at Object.sortJsxElement (D:\Projects\sortier\src\sortJsxElement\index.ts:27:15)
      at Context.it (D:\Projects\sortier\src\sortJsxElement\index.test.ts:72:26)

**Comment by k2snowman69** [comment]
https://github.com/snowcoders/sortier/pull/85 - Will go out with 2.1.9 or later
